# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#                     EnchantmentLock Settings                    #
#                              by Newt                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# Items with a lore containing one of these identifiers cannot be enchanted.
# The words in this list are case-sensitive.
identifiers:
  - "Enchanting disabled"
  - "enchanting disabled"
  - "Locked"
  - "locked"
  - "Closed"
  - "closed"

# Message send to players when they try to modify a locked item.
# Supports colour codes ("&").
cannot_enchant: "&cThis item cannot be enchanted."
cannot_disenchant: "&cThe enchantments on this item cannot be removed."
cannot_repair: "&cThis item cannot be repaired."
cannot_smith: "&cThis item cannot be upgraded to netherite."
cannot_rename: "&cThis item cannot be renamed."

# Toggle parts of the plugin. By default, all ways to (dis)enchant an item are prevented.
# Prevent players from enchanting locked items with an Enchanting Table.
block_enchanting_table: true

# Prevent players from enchanting locked items with an Anvil.
block_anvil_enchanting: true

# Prevent players from repairing & combining locked items with an Anvil.
block_anvil_repair: true

# Prevent players from changing the name of locked items with an Anvil.
block_name_change: true

# Prevent players from disenchanting locked items with a Grindstone.
block_grindstone: true

# Prevent players from upgrading locked items to netherite with a smithing table.
block_smithing: true

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#                  Do not change the value below.                 #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
config_version: 1
